### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by dohyun-as** [mui-neuro/swi-cnn#1]
Hi!

I would like to ask some questions regarding trained models. Trained models have only unet, unetpp and vnet. Can I get FC-Dense Net, and Dilated FC-Dense Net. And I want to know mean of patch image.

Thanks!

**Comment by vbeliveau** [comment]
Hi @DH1929ds , thanks for noting that the some models were missing. I've now updated the models archive (https://download.i-med.ac.at/neuro/archive/swi-cnn_models.tar.gz) to include FC-Dense Net and Dilated FC-Dense Net. I've also remove some additional path models that had not been trained on the full dataset (only UNet++ had been), thus reducing the size of the archive by half.

Concerning "And I want to know mean of patch image.", you mean that you'd like to predict the location of the patch using multiple models and get the average? I'm afraid that since only one final patch model is available (i.e., UNet++), this won't be possible. Training new models with your own data should be relatively easy though.

**Comment by dohyun-as** [comment]
Thank you for your quick reply. I will try again!
